/* 金曲猜歌王 — 題庫(223 首)
 *
 * 這 223 首是「會被當成題目」的歌,每一首都需要音源
 * (audio/<id>.m4a 本地檔,或 previews.js 裡的官方試聽網址)。
 *
 * 每一局固定抽 10 題,抽法寫在 index.html 的 CONFIG:
 *   保底配額 華語現代 5 · 華語經典 1 · 台語 1,再保底 1 題非中文(韓/西洋/日文),
 *   剩下 2 題從全部歌曲隨機補 —— 所以非中文至少 1 題,但可能更多。
 * 配額之內隨機抽,出題順序也是隨機的。
 *
 * genre 有兩個用途,但玩家在畫面上完全看不到它:
 *   1. 決定上面那個配額
 *   2. 挑干擾選項 —— 華語歌的九宮格要配華語的干擾項,
 *      不然一堆英文選項混進來,用刪去法就猜到了
 *
 * 純干擾用的歌名(不需要音源)放在 decoys.js。
 */
window.SONGS = [
  /* ---------- 華語現代 ---------- */
  { id: "daoxiang",           title: "稻香",                          artist: "周杰倫",         genre: "mando" },
  { id: "qingtian",           title: "晴天",                          artist: "周杰倫",         genre: "mando" },
  { id: "gaobaiqiqiu",        title: "告白氣球",                      artist: "周杰倫",         genre: "mando" },
  { id: "wenrou",             title: "溫柔",                          artist: "五月天",         genre: "mando" },
  { id: "turanhaoxiangni",    title: "突然好想你",                    artist: "五月天",         genre: "mando" },
  { id: "xiulianaiqing",      title: "修煉愛情",                      artist: "林俊傑",         genre: "mando" },
  { id: "jiangnan",           title: "江南",                          artist: "林俊傑",         genre: "mando" },
  { id: "xiaoxingyun",        title: "小幸運",                        artist: "田馥甄",         genre: "mando" },
  { id: "shuohuang",          title: "說謊",                          artist: "林宥嘉",         genre: "mando" },
  { id: "shinian",            title: "十年",                          artist: "陳奕迅",         genre: "mando" },
  { id: "guangnianzhiwai",    title: "光年之外",                      artist: "鄧紫棋",         genre: "mando" },
  { id: "haoburongyi",        title: "好不容易",                      artist: "告五人",         genre: "mando" },
  { id: "yuzai",              title: "魚仔",                          artist: "盧廣仲",         genre: "mando" },
  { id: "xiaoqingge",         title: "小情歌",                        artist: "蘇打綠",         genre: "mando" },
  { id: "yujian",             title: "遇見",                          artist: "孫燕姿",         genre: "mando" },
  { id: "ribuluo",            title: "日不落",                        artist: "蔡依林",         genre: "mando" },
  { id: "yihoubiezuo",        title: "以後別做朋友",                  artist: "周興哲",         genre: "mando" },
  { id: "yanyuan",            title: "演員",                          artist: "薛之謙",         genre: "mando" },
  { id: "xiaochou",           title: "消愁",                          artist: "毛不易",         genre: "mando" },
  { id: "shuixingji",         title: "水星記",                        artist: "郭頂",           genre: "mando" },
  { id: "xiangjianni",        title: "想見你想見你想見你",            artist: "八三夭",         genre: "mando" },
  { id: "haonianqing",        title: "我還年輕 我還年輕",             artist: "老王樂隊",       genre: "mando" },
  { id: "qifengle",           title: "起風了",                        artist: "買辣椒也用券",   genre: "mando" },
  { id: "shuosanjiusan",      title: "說散就散",                      artist: "JC 陳詠桐",      genre: "mando" },
  { id: "dayu",               title: "大魚",                          artist: "周深",           genre: "mando" },
  { id: "wangfei",            title: "王妃",                          artist: "蕭敬騰",         genre: "mando" },
  { id: "shenqibaima",        title: "身騎白馬",                      artist: "徐佳瑩",         genre: "mando" },
  { id: "shishenmerang",      title: "是什麼讓我遇見這樣的你",        artist: "白安",           genre: "mando" },
  { id: "aimei",              title: "曖昧",                          artist: "楊丞琳",         genre: "mando" },
  { id: "superstar",          title: "Super Star",                    artist: "S.H.E",          genre: "mando" },
  { id: "zuishouxi",          title: "最熟悉的陌生人",                artist: "蕭亞軒",         genre: "mando" },
  { id: "nibuzhidao",         title: "你不知道的事",                  artist: "王力宏",         genre: "mando" },
  { id: "jiushiaini",         title: "就是愛你",                      artist: "陶喆",           genre: "mando" },
  { id: "libai",              title: "李白",                          artist: "李榮浩",         genre: "mando" },
  { id: "dang",               title: "當",                            artist: "動力火車",       genre: "mando" },
  { id: "shoufangkai",        title: "手放開",                        artist: "李聖傑",         genre: "mando" },
  { id: "kongbaige",          title: "空白格",                        artist: "蔡健雅",         genre: "mando" },
  { id: "lvxingdeyiyi",       title: "旅行的意義",                    artist: "陳綺貞",         genre: "mando" },
  { id: "yinxingdechibang",   title: "隱形的翅膀",                    artist: "張韶涵",         genre: "mando" },
  { id: "womendeai",          title: "我們的愛",                      artist: "F.I.R.",         genre: "mando" },
  { id: "haoxiangni",         title: "好想你",                        artist: "朱主愛",         genre: "mando" },
  { id: "qishidoumeiyou",     title: "其實都沒有",                    artist: "楊宗緯",         genre: "mando" },
  { id: "yigerenxiangzhe",    title: "一個人想著一個人",              artist: "曾沛慈",         genre: "mando" },
  { id: "naxienian",          title: "那些年",                        artist: "胡夏",           genre: "mando" },
  { id: "haishihui",          title: "還是會",                        artist: "韋禮安",         genre: "mando" },
  { id: "aini",               title: "愛你",                          artist: "陳芳語",         genre: "mando" },
  { id: "zhuiguangzhe",       title: "追光者",                        artist: "岑寧兒",         genre: "mando" },
  { id: "zenyang",            title: "怎樣",                          artist: "戴佩妮",         genre: "mando" },
  { id: "qinghuaci",          title: "青花瓷",                        artist: "周杰倫",         genre: "mando" },
  { id: "shuohaobuku",        title: "說好不哭",                      artist: "周杰倫",         genre: "mando" },
  { id: "juejiang",           title: "倔強",                          artist: "五月天",         genre: "mando" },
  { id: "lianaiing",          title: "戀愛ing",                       artist: "五月天",         genre: "mando" },
  { id: "yangcong",           title: "洋蔥",                          artist: "五月天",         genre: "mando" },
  { id: "tashuo",             title: "她說",                          artist: "林俊傑",         genre: "mando" },
  { id: "xiaojiuwo",          title: "小酒窩",                        artist: "林俊傑",         genre: "mando" },
  { id: "moguizhongde",       title: "魔鬼中的天使",                  artist: "田馥甄",         genre: "mando" },
  { id: "langfei",            title: "浪費",                          artist: "林宥嘉",         genre: "mando" },
  { id: "xiangziyou",         title: "想自由",                        artist: "林宥嘉",         genre: "mando" },
  { id: "aiqingzhuanyi",      title: "愛情轉移",                      artist: "陳奕迅",         genre: "mando" },
  { id: "paomo",              title: "泡沫",                          artist: "鄧紫棋",         genre: "mando" },
  { id: "xihuanni",           title: "喜歡你",                        artist: "鄧紫棋",         genre: "mando" },
  { id: "yeshenghuo",         title: "帶我去找夜生活",                artist: "告五人",         genre: "mando" },
  { id: "airencuoguo",        title: "愛人錯過",                      artist: "告五人",         genre: "mando" },
  { id: "kezaixindi",         title: "刻在我心底的名字",              artist: "盧廣仲",         genre: "mando" },
  { id: "wohaoxiangni",       title: "我好想你",                      artist: "蘇打綠",         genre: "mando" },
  { id: "tianheihei",         title: "天黑黑",                        artist: "孫燕姿",         genre: "mando" },
  { id: "wohuainiande",       title: "我懷念的",                      artist: "孫燕姿",         genre: "mando" },
  { id: "meiguishaonian",     title: "玫瑰少年",                      artist: "蔡依林",         genre: "mando" },
  { id: "zenmele",            title: "怎麼了",                        artist: "周興哲",         genre: "mando" },
  { id: "choubagua",          title: "醜八怪",                        artist: "薛之謙",         genre: "mando" },
  { id: "xiangwozheyang",     title: "像我這樣的人",                  artist: "毛不易",         genre: "mando" },
  { id: "beipan",             title: "背叛",                          artist: "曹格",           genre: "mando" },
  { id: "haoxinfenshou",      title: "好心分手",                      artist: "盧巧音",         genre: "mando" },
  { id: "shouzhangxin",       title: "手掌心",                        artist: "丁噹",           genre: "mando" },
  { id: "pingfanzhilu",       title: "平凡之路",                      artist: "朴樹",           genre: "mando" },
  { id: "dongxiaojie",        title: "董小姐",                        artist: "宋冬野",         genre: "mando" },
  { id: "nanshannan",         title: "南山南",                        artist: "馬頔",           genre: "mando" },
  { id: "chengdu",            title: "成都",                          artist: "趙雷",           genre: "mando" },
  { id: "lanlianhua",         title: "藍蓮花",                        artist: "許巍",           genre: "mando" },
  { id: "youdiantian",        title: "有點甜",                        artist: "汪蘇瀧",         genre: "mando" },
  { id: "xiaopingguo",        title: "小蘋果",                        artist: "筷子兄弟",       genre: "mando" },
  { id: "yiluxiangbei",       title: "一路向北",                      artist: "周杰倫",         genre: "mando" },
  { id: "shangxinderen",      title: "傷心的人別聽慢歌",              artist: "五月天",         genre: "mando" },
  { id: "jimojiuhao",         title: "寂寞寂寞就好",                  artist: "田馥甄",         genre: "mando" },
  { id: "wuyulunbi",          title: "無與倫比的美麗",                artist: "蘇打綠",         genre: "mando" },
  { id: "shuoaini",           title: "說愛你",                        artist: "蔡依林",         genre: "mando" },
  { id: "nihaobuhao",         title: "你,好不好?",                    artist: "周興哲",         genre: "mando" },
  { id: "ganggangahao",       title: "剛剛好",                        artist: "薛之謙",         genre: "mando" },
  { id: "ruguokeyi",          title: "如果可以",                      artist: "韋禮安",         genre: "mando" },
  { id: "nianshaoyouwei",     title: "年少有為",                      artist: "李榮浩",         genre: "mando" },
  { id: "hongsegaogenxie",    title: "紅色高跟鞋",                    artist: "蔡健雅",         genre: "mando" },
  { id: "ouruola",            title: "歐若拉",                        artist: "張韶涵",         genre: "mando" },
  { id: "buxiangzhangda",     title: "不想長大",                      artist: "S.H.E",          genre: "mando" },
  { id: "dachengxiaoai",      title: "大城小愛",                      artist: "王力宏",         genre: "mando" },
  { id: "aihenjiandan",       title: "愛很簡單",                      artist: "陶喆",           genre: "mando" },
  { id: "chixinjuedui",       title: "痴心絕對",                      artist: "李聖傑",         genre: "mando" },
  { id: "shanhai",            title: "山海",                          artist: "草東沒有派對",   genre: "mando" },
  { id: "niania",             title: "你啊你啊",                      artist: "魏如萱",         genre: "mando" },
  { id: "youyizhongbeishang", title: "有一種悲傷",                    artist: "A-Lin",          genre: "mando" },
  { id: "yicijiuhao",         title: "一次就好",                      artist: "楊宗緯",         genre: "mando" },
  { id: "xiaoban",            title: "小半",                          artist: "陳粒",           genre: "mando" },
  { id: "nidedaan",           title: "你的答案",                      artist: "阿冗",           genre: "mando" },
  { id: "lvse",               title: "綠色",                          artist: "陳雪凝",         genre: "mando" },
  { id: "ainidanshuo",        title: "愛你但說不出口",                artist: "Karencici",      genre: "mando" },
  { id: "nianlun",            title: "年輪",                          artist: "張碧晨",         genre: "mando" },
  { id: "anheqiao",           title: "安和橋",                        artist: "宋冬野",         genre: "mando" },
  { id: "yanhuochenai",       title: "煙火裡的塵埃",                  artist: "華晨宇",         genre: "mando" },
  { id: "tiaolouji",          title: "跳樓機",                        artist: "LBI利比",        genre: "mando" },
  { id: "taiyangdiqiu",       title: "太陽與地球",                    artist: "盧廣仲",         genre: "mando" },
  { id: "xingfugechang",      title: "幸福在歌唱",                    artist: "A-Lin",          genre: "mando" },
  { id: "jiayibingding",      title: "甲乙丙丁",                      artist: "李佳薇",         genre: "mando" },
  { id: "boli",               title: "玻璃",                          artist: "Gareth.T",       genre: "mando" },
  { id: "dafengchui",         title: "大風吹",                        artist: "草東沒有派對",   genre: "mando" },
  { id: "anjiu",              title: "安九",                          artist: "老王樂隊",       genre: "mando" },
  { id: "wendingshenghuo",    title: "穩定生活多美好 三年五年高普考", artist: "老王樂隊",       genre: "mando" },
  { id: "myjinji",            title: "My Jinji",                      artist: "落日飛車",       genre: "mando" },
  { id: "meihaodeshi",        title: "美好的事可不可以發生在我身上",  artist: "康士坦的變化球", genre: "mando" },
  { id: "yushi",              title: "浴室",                          artist: "deca joins",     genre: "mando" },
  { id: "meiyongnianqing",    title: "他們說我是沒有用的年輕人",      artist: "好樂團",         genre: "mando" },
  { id: "likaiyilushang",     title: "離開的一路上",                  artist: "理想混蛋",       genre: "mando" },
  { id: "tianqiqinglang",     title: "不是因為天氣晴朗才愛你",        artist: "理想混蛋",       genre: "mando" },
  { id: "meiyourenxiang",     title: "沒有人像我一樣",                artist: "宇宙人",         genre: "mando" },
  { id: "shiaidongwu",        title: "嗜愛動物",                      artist: "麋先生",         genre: "mando" },
  { id: "nizhongjiu",         title: "你終究不愛這世界",              artist: "傻子與白痴",     genre: "mando" },
  { id: "taibeiliulang",      title: "台北流浪指南",                  artist: "傷心欲絕",       genre: "mando" },
  { id: "lydia",              title: "Lydia",                         artist: "F.I.R.",         genre: "mando" },
  { id: "yu",                 title: "魚",                            artist: "怕胖團",         genre: "mando" },
  { id: "yuepangyueguang",    title: "月旁月光",                      artist: "怕胖團",         genre: "mando" },
  { id: "lansedeni",          title: "藍色的你",                      artist: "宇宙人",         genre: "mando" },
  { id: "ruguohaizaiyiqi",    title: "如果我們還在一起",              artist: "宇宙人",         genre: "mando" },
  { id: "dahuaidan",          title: "愛情的大壞蛋",                  artist: "美秀集團",       genre: "mando" },
  { id: "shoujiqianbao",      title: "手機錢包鑰匙菸",                artist: "美秀集團",       genre: "mando" },
  { id: "balidezhou",         title: "巴黎德州",                      artist: "椅子樂團",       genre: "mando" },
  { id: "shizongrenkou",      title: "失蹤人口",                      artist: "甜約翰",         genre: "mando" },
  { id: "beishangbeishang",   title: "揹上悲傷北上",                  artist: "Crispy 脆樂團",  genre: "mando" },
  { id: "meiyourenzaihu",     title: "沒有人在乎你在乎的事",          artist: "那我懂你意思了", genre: "mando" },
  { id: "zhaobudaolangman",   title: "在這個年代,找不到浪漫",         artist: "溫室雜草",       genre: "mando" },
  { id: "qingchungeini",      title: "我把我的青春給你",              artist: "好樂團",         genre: "mando" },
  { id: "naxieshimiandeye",   title: "那些失眠的夜與難以忘懷的事",    artist: "老王樂隊",       genre: "mando" },
  { id: "dan",                title: "但",                            artist: "草東沒有派對",   genre: "mando" },
  { id: "woshiyizhiyu",       title: "我是一隻魚",                    artist: "落日飛車",       genre: "mando" },
  { id: "geqianderen",        title: "擱淺的人",                      artist: "康士坦的變化球", genre: "mando" },
  { id: "jiuerling",          title: "920",                           artist: "A-Lin",          genre: "mando" },
  { id: "crushon",            title: "Crush on",                      artist: "李浩瑋",         genre: "mando" },
  { id: "zhenxinhua",         title: "真心話",                        artist: "李浩瑋",         genre: "mando" },
  { id: "jisuanlangman",      title: "計算浪漫",                      artist: "艾薇",           genre: "mando" },
  { id: "buaijiubuai",        title: "不愛就不愛",                    artist: "艾薇",           genre: "mando" },
  { id: "diqiubaozha",        title: "在地球爆炸之前",                artist: "理想混蛋",       genre: "mando" },
  { id: "nideweixiao",        title: "你的微笑",                      artist: "F.I.R.",         genre: "mando" },
  { id: "chongai",            title: "寵愛",                          artist: "TFBOYS",         genre: "mando" },
  /* ---------- 華語經典 ---------- */
  { id: "tianmimi",        title: "甜蜜蜜",         artist: "鄧麗君", genre: "classic" },
  { id: "zhishaohaiyouni", title: "至少還有你",     artist: "林憶蓮", genre: "classic" },
  { id: "wenbie",          title: "吻別",           artist: "張學友", genre: "classic" },
  { id: "hongdou",         title: "紅豆",           artist: "王菲",   genre: "classic" },
  { id: "tinghai",         title: "聽海",           artist: "張惠妹", genre: "classic" },
  { id: "pengyou",         title: "朋友",           artist: "周華健", genre: "classic" },
  { id: "yongqi",          title: "勇氣",           artist: "梁靜茹", genre: "classic" },
  { id: "xiaoxiaoniao",    title: "我是一隻小小鳥", artist: "趙傳",   genre: "classic" },
  { id: "tonghua",         title: "童話",           artist: "光良",   genre: "classic" },
  { id: "sileduyaoai",     title: "死了都要愛",     artist: "信樂團", genre: "classic" },
  { id: "qingfeideyi",     title: "情非得已",       artist: "庾澄慶", genre: "classic" },
  { id: "wangqingshui",    title: "忘情水",         artist: "劉德華", genre: "classic" },
  { id: "tiantianxiangni", title: "天天想你",       artist: "張雨生", genre: "classic" },
  { id: "xintairuan",      title: "心太軟",         artist: "任賢齊", genre: "classic" },
  { id: "yintian",         title: "陰天",           artist: "莫文蔚", genre: "classic" },
  { id: "yongxinliangku",  title: "用心良苦",       artist: "張宇",   genre: "classic" },
  { id: "weidao",          title: "味道",           artist: "辛曉琪", genre: "classic" },
  { id: "dayuezaidongji",  title: "大約在冬季",     artist: "齊秦",   genre: "classic" },
  { id: "yichangyouxi",    title: "一場遊戲一場夢", artist: "王傑",   genre: "classic" },
  { id: "tongnian",        title: "童年",           artist: "羅大佑", genre: "classic" },
  { id: "zhengfu",         title: "征服",           artist: "那英",   genre: "classic" },
  { id: "guohuo",          title: "過火",           artist: "張信哲", genre: "classic" },
  { id: "yazi",            title: "鴨子",           artist: "蘇慧倫", genre: "classic" },
  { id: "aiwobiezou",      title: "愛我別走",       artist: "張震嶽", genre: "classic" },
  { id: "houlai",          title: "後來",           artist: "劉若英", genre: "classic" },
  { id: "huanghun",        title: "黃昏",           artist: "周傳雄", genre: "classic" },
  { id: "woyuanyi",        title: "我願意",         artist: "王菲",   genre: "classic" },
  { id: "nvrenhua",        title: "女人花",         artist: "梅艷芳", genre: "classic" },
  { id: "yueliang",        title: "月亮代表我的心", artist: "鄧麗君", genre: "classic" },
  { id: "wuding",          title: "屋頂",           artist: "溫嵐",   genre: "classic" },
  { id: "jianai",          title: "剪愛",           artist: "張惠妹", genre: "classic" },
  { id: "xinbuleqing",     title: "新不了情",       artist: "萬芳",   genre: "classic" },
  { id: "nuoweisenlin",    title: "挪威的森林",     artist: "伍佰",   genre: "classic" },
  { id: "lingwu",          title: "領悟",           artist: "辛曉琪", genre: "classic" },
  { id: "nuannuan",        title: "暖暖",           artist: "梁靜茹", genre: "classic" },
  /* ---------- 台語 ---------- */
  { id: "langzihuitou",    title: "浪子回頭",         artist: "茄子蛋",     genre: "tw" },
  { id: "chiqingnanzihan", title: "癡情男子漢",       artist: "玖壹壹",     genre: "tw" },
  { id: "nishiwodehuaduo", title: "妳是我的花朵",     artist: "伍佰",       genre: "tw" },
  { id: "daoyutianguang",  title: "島嶼天光",         artist: "滅火器",     genre: "tw" },
  { id: "jiahou",          title: "家後",             artist: "江蕙",       genre: "tw" },
  { id: "amadehua",        title: "阿嬤的話",         artist: "蕭煌奇",     genre: "tw" },
  { id: "shijiediyideng",  title: "世界第一等",       artist: "伍佰",       genre: "tw" },
  { id: "wunv",            title: "舞女",             artist: "陳小雲",     genre: "tw" },
  { id: "huanxijiuhao",    title: "歡喜就好",         artist: "陳雷",       genre: "tw" },
  { id: "langliulian",     title: "浪流連",           artist: "茄子蛋",     genre: "tw" },
  { id: "wanqianhuarui",   title: "萬千花蕊慈母悲哀", artist: "珂拉琪",     genre: "tw" },
  { id: "danggen",         title: "擋一根",           artist: "美秀集團",   genre: "tw" },
  { id: "xinmen",          title: "心悶",             artist: "美秀集團",   genre: "tw" },
  { id: "anliu",           title: "暗流",             artist: "拍謝少年",   genre: "tw" },
  { id: "dakaitaiyang",    title: "打開太陽",         artist: "血肉果汁機", genre: "tw" },
  /* ---------- 韓語 ---------- */
  { id: "dynamite",       title: "Dynamite",          artist: "BTS",          genre: "kpop" },
  { id: "gangnamstyle",   title: "Gangnam Style",     artist: "PSY",          genre: "kpop" },
  { id: "howyoulikethat", title: "How You Like That", artist: "BLACKPINK",    genre: "kpop" },
  { id: "ditto",          title: "Ditto",             artist: "NewJeans",     genre: "kpop" },
  { id: "tt",             title: "TT",                artist: "TWICE",        genre: "kpop" },
  { id: "tomboy",         title: "TOMBOY",            artist: "(G)I-DLE",     genre: "kpop" },
  { id: "sorrysorry",     title: "Sorry, Sorry",      artist: "Super Junior", genre: "kpop" },
  { id: "bluevalentine",  title: "Blue Valentine",    artist: "NMIXX",        genre: "kpop" },
  { id: "antifragile",    title: "ANTIFRAGILE",       artist: "LE SSERAFIM",  genre: "kpop" },
  { id: "supernova",      title: "Supernova",         artist: "aespa",        genre: "kpop" },
  { id: "growl",          title: "Growl",             artist: "EXO",          genre: "kpop" },
  { id: "psycho",         title: "Psycho",            artist: "Red Velvet",   genre: "kpop" },
  { id: "verynice",       title: "Very Nice",         artist: "SEVENTEEN",    genre: "kpop" },
  { id: "gee",            title: "Gee",               artist: "少女時代",     genre: "kpop" },
  { id: "apt",            title: "APT.",              artist: "ROSÉ",         genre: "kpop" },
  { id: "golden",         title: "Golden",            artist: "HUNTR/X",      genre: "kpop" },
  { id: "killthislove",   title: "Kill This Love",    artist: "BLACKPINK",    genre: "kpop" },
  { id: "whatislove",     title: "What Is Love?",     artist: "TWICE",        genre: "kpop" },
  { id: "queencard",      title: "Queencard",         artist: "(G)I-DLE",     genre: "kpop" },
  { id: "nextlevel",      title: "Next Level",        artist: "aespa",        genre: "kpop" },
  { id: "magnetic",       title: "Magnetic",          artist: "ILLIT",        genre: "kpop" },
  { id: "bangbangbang",   title: "Bang Bang Bang",    artist: "BIGBANG",      genre: "kpop" },
  { id: "nobody",         title: "Nobody",            artist: "Wonder Girls", genre: "kpop" },
  { id: "whiplash",       title: "Whiplash",          artist: "aespa",        genre: "kpop" },
  { id: "strategy",       title: "Strategy",          artist: "TWICE",        genre: "kpop" },
  { id: "overdrive",      title: "Overdrive",         artist: "TWS",          genre: "kpop" },
  { id: "day6happy",      title: "HAPPY",             artist: "DAY6",         genre: "kpop" },
  { id: "dinosaur",       title: "DINOSAUR",          artist: "AKMU",         genre: "kpop" },
  { id: "mrchu",          title: "Mr. Chu",           artist: "Apink",        genre: "kpop" },
  /* ---------- 西洋 ---------- */
  { id: "shapeofyou",     title: "Shape of You",                    artist: "Ed Sheeran",        genre: "west" },
  { id: "blindinglights", title: "Blinding Lights",                 artist: "The Weeknd",        genre: "west" },
  { id: "someonelikeyou", title: "Someone Like You",                artist: "Adele",             genre: "west" },
  { id: "badguy",         title: "Bad Guy",                         artist: "Billie Eilish",     genre: "west" },
  { id: "shakeitoff",     title: "Shake It Off",                    artist: "Taylor Swift",      genre: "west" },
  { id: "uptownfunk",     title: "Uptown Funk",                     artist: "Mark Ronson",       genre: "west" },
  { id: "countingstars",  title: "Counting Stars",                  artist: "OneRepublic",       genre: "west" },
  { id: "letitgo",        title: "Let It Go",                       artist: "Idina Menzel",      genre: "west" },
  { id: "despacito",      title: "Despacito",                       artist: "Luis Fonsi",        genre: "west" },
  { id: "happy",          title: "Happy",                           artist: "Pharrell Williams", genre: "west" },
  { id: "flowers",        title: "Flowers",                         artist: "Miley Cyrus",       genre: "west" },
  { id: "attention",      title: "Attention",                       artist: "Charlie Puth",      genre: "west" },
  { id: "believer",       title: "Believer",                        artist: "Imagine Dragons",   genre: "west" },
  { id: "vivalavida",     title: "Viva La Vida",                    artist: "Coldplay",          genre: "west" },
  { id: "baby",           title: "Baby",                            artist: "Justin Bieber",     genre: "west" },
  { id: "nothingholding", title: "There's Nothing Holdin' Me Back", artist: "Shawn Mendes",      genre: "west" },
  { id: "whatmakesyou",   title: "What Makes You Beautiful",        artist: "One Direction",     genre: "west" },
  /* ---------- 日文 / 動漫 ---------- */
  { id: "lemon",         title: "Lemon",                artist: "米津玄師",         genre: "jp" },
  { id: "idol",          title: "Idol",                 artist: "YOASOBI",          genre: "jp" },
  { id: "gurenge",       title: "紅蓮華",               artist: "LiSA",             genre: "jp" },
  { id: "pretender",     title: "Pretender",            artist: "Official髭男dism", genre: "jp" },
  { id: "zankyosanka",   title: "残響散歌",             artist: "Aimer",            genre: "jp" },
  { id: "zenzenzense",   title: "前前前世",             artist: "RADWIMPS",         genre: "jp" },
  { id: "yorunikakeru",  title: "夜に駆ける",           artist: "YOASOBI",          genre: "jp" },
  { id: "gunjo",         title: "群青",                 artist: "YOASOBI",          genre: "jp" },
  { id: "uchiagehanabi", title: "打上花火",             artist: "米津玄師",         genre: "jp" },
  { id: "homura",        title: "炎",                   artist: "LiSA",             genre: "jp" },
  { id: "bbbb",          title: "Bling-Bang-Bang-Born", artist: "Creepy Nuts",      genre: "jp" },
  { id: "firstlove",     title: "First Love",           artist: "宇多田ヒカル",     genre: "jp" },
  { id: "ganzaohua",     title: "乾燥花",               artist: "優里",             genre: "jp" },
  { id: "wancange",      title: "晩餐歌",               artist: "tuki.",            genre: "jp" }
];
